version: '2'
services:
  actions-runner:
    network_mode: host
    restart: always
    build: ./actions-runner
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
